"""empty message

Revision ID: 34743e02ef48
Revises: 0d819ccf190d
Create Date: 2020-04-04 19:13:10.187957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34743e02ef48'
down_revision = '0d819ccf190d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'num_upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('num_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
